### ISSUE TITLE
add licence

### ISSUE THREAD

**Issue by marianoguerra** [tonylukasavage/jsstl#5]
the code needs a license mention in the README and a LICENSE file, otherwise it can't be legally used by others.

I can open a PR if you tell me which license you would like to use for it.

PS: virtual high five :)

**Comment by marianoguerra** [comment]
just as a note, given the "Do whatever you want with this code" comment in the readme I would recommend MIT or BSD

**Comment by StefanJanssen95** [comment]
I think a [DBAD license](https://dbad-license.org/) would be a better fit.

**Comment by StefanJanssen95** [comment]
Why would it be a joke? "Do whatever you want" is basically the same as the DBAD license. MIT and BSD do have a bit more limitations.

**Comment by marianoguerra** [comment]
show that to a lawyer, she will explain it

**Comment by StefanJanssen95** [comment]
There should not be a different between a more common license or one written yourself. A license is still a license. There really is no need for complicated words, the license itself is really clear on what one can and cannot do.

**Comment by marianoguerra** [comment]
from what you say it seems that lawyers, judges, contracts, laws and all law related activities aren't needed, or that they can be done by anyone and there are no potential downsides to it.

**Comment by StefanJanssen95** [comment]
This is just putting words in my mouth. I dont say that at all. All I say that complicated words and long licenses are not needed for a valid license. The original author of this project states "Do whatever you want with it" a DBAD license fits fine with that. 

If one wants credit for it an MIT or BSD license are better since that is required by the license. A DBAD license doesn't state that that is necessary. You can actually do whatever you want with it as long as you are not a dick (as more specifically described in the license)

**Comment by marianoguerra** [comment]
I worked for organizations that had to review every dependency and license and those licenses were not valid. 

You are saying that a legal document specifying the usage permissions on a piece of code can have the word "dick" in it and that clearly tells me and others that it wasn't created by a professional lawyer, someone who had to study to craft legal documents for other lawyers to read, evaluate and defend in court if necessary. 

Maybe you understand it this way: that license won't even compile for a lawyer.

I understand that we programmers think we are smarter and we can create legal documents, solve the economy, poverty and all other problems "from first principle" or that things that other professions do are easy or plain unnecessary. They are not.

In case you just enjoy trying to win arguments just for the fun of it, I'm over with this. Have fun being smarter than everybody else.
